/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider/index.vue')['default']
    BasicButton: typeof import('./src/components/BasicButton/BasicButton.vue')['default']
    BasicInput: typeof import('./src/components/BasicInput/index.vue')['default']
    Iconify: typeof import('./src/components/Iconify/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test/index.vue')['default']
  }
}
